#on: push
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
    - name: check-out-this-repo-step
      uses: actions/checkout@v2
      with:
        path: AzureMLtest
    - name: check-out-azureml-examples-repo-step
      uses: actions/checkout@v3
      with:
        repository: Azure/azureml-examples
        path: azureml-examples
    - id: set-matrix
        run: echo '::set-output name=version_matrix::["basics/3a_basic_pipeline","basics/4a_local_data_input"]'
    outputs:
      version_matrix: ${{ steps.set-matrix.outputs.version_matrix }}
  ci:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.build-matrix.outputs.version_matrix) }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "this is the version - ${{ matrix.version }}"