#on: push

env:
  GROUP: junqitest-rg
  LOCATION: centraluseuap
  WORKSPACE: junqitest
  REGISTRY: testFeed
# set this if private CLI has to be installed, else comment out
  CLI: https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.63239653-py3-none-any.whl
# set this env var if the CLI uses private preview features
  AZURE_ML_CLI_PRIVATE_FEATURES_ENABLED: true


jobs:
  populate-assets-job:
    runs-on: ubuntu-latest
    steps:
    - name: check-out-this-repo-step
      uses: actions/checkout@v2
      with:
        path: AzureMLtest
    - name: azure-login-step
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - name: set-azureml-ws-context-step
      run: bash setup.sh 
      working-directory: AzureMLtest/cli
    - name: populate-assets
      run: bash populate-assets.sh registry
      #continue-on-error: true
      working-directory: AzureMLtest/cli
