on: 
  push:

env:
  GROUP: junqitest-rg
  LOCATION: centraluseuap
  WORKSPACE: junqitest
  REGISTRY: testFeed
# set this if private CLI has to be installed, else comment out
  CLI: https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.61212840-py3-none-any.whl


jobs:
  list-components-job:
    runs-on: ubuntu-latest
    steps:
    - name: check-out-this-repo-step
      uses: actions/checkout@v2
      with:
        path: this
    - name: check-out-azureml-examples-repo-step
      uses: actions/checkout@v3
      with:
        repository: Azure/azureml-examples
        path: azureml-examples
    - name: azure-login-step
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - run: pwd
   # - name: set-azureml-ws-context-step
   #   run: bash setup.sh 
   #   working-directory: $GITHUB_WORKSPACE/this/AzureMLtest/cli
