on: 
  push:

env:
#  GROUP:  junqicanary-rg
#  LOCATION: eastus2euap
#  WORKSPACE: junqicanary-ws
#  REGISTRY: junqicanary-newregistry
#  SUB: ea4faa5b-5e44-4236-91f6-5483d5b17d14
  GROUP:  OpenDatasetsPMRG
  LOCATION: eastus2
  WORKSPACE: OpenDatasetsPMWorkspace
  REGISTRY: ContosoML
  SUB: 21d8f407-c4c4-452e-87a4-e609bfb86248
# uncommeting this run all commands in debug mode
  DEBUG: "--debug"
# set this if private CLI has to be installed, else comment out
#  CLI: https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.63239653-py3-none-any.whl
  CLI: https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.63572232-py3-none-any.whl
# set this env var if the CLI uses private preview features
  AZURE_ML_CLI_PRIVATE_FEATURES_ENABLED: true
  COMPONENT_SAMPLE_ROOT: ../../azureml-examples/cli/jobs/pipelines-with-components/
  ENVIRONMENT_SAMPLE_ROOT: ../../azureml-examples/cli/assets/environment
  PIPELINE_YAML: pipeline.yml


jobs:
  list-components-job:
  #  if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    steps:
    - name: check-out-this-repo-step
      uses: actions/checkout@v2
      with:
        path: AzureMLtest
    - name: check-out-azureml-examples-repo-step
      uses: actions/checkout@v3
      with:
        repository: Azure/azureml-examples
        path: azureml-examples
#    - name: azure-login-step
#      uses: azure/login@v1
#      with:
#        creds: ${{secrets.AZ_CREDS}}
#    - name: set-azureml-ws-context-step
#      run: bash setup.sh 
#      working-directory: AzureMLtest/cli
    - name: list-component-samples-step
      id: list-component-samples-step
#      run: bash list-component-samples.sh
      run: echo '::set-output name=sample_matrix::["nyc_taxi_data_regression", "basics/5a_env_public_docker_image", "basics/5c_env_conda_file"]'
#      run: echo '::set-output name=sample_matrix::["basics/1a_e2e_local_components"]'
      working-directory: AzureMLtest/cli
    outputs:
      component_sample_matrix: ${{ steps.list-component-samples-step.outputs.sample_matrix }}

  test-component-workspace:
  #  if: ${{ false }}  # disable for now
    continue-on-error: true 
    needs: list-components-job
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        component_sample: ${{ fromJson(needs.list-components-job.outputs.component_sample_matrix) }}
    steps:
    - name: check-out-this-repo-step
      uses: actions/checkout@v2
      with:
        path: AzureMLtest
    - name: check-out-azureml-examples-repo-step
      uses: actions/checkout@v3
      with:
        repository: Azure/azureml-examples
        path: azureml-examples
    - name: azure-login-step
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - name: set-azureml-ws-context-step
      run: bash setup.sh 
      working-directory: AzureMLtest/cli
    - name: register-components-and-run-job-workspace-step
      run: bash test-component.sh ${{ matrix.component_sample }} workspace
      continue-on-error: true
      working-directory: AzureMLtest/cli

  test-component-registry:
  #  if: ${{ false }}  # disable for now
    needs: list-components-job
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        component_sample: ${{ fromJson(needs.list-components-job.outputs.component_sample_matrix) }}
    steps:
    - name: check-out-this-repo-step
      uses: actions/checkout@v2
      with:
        path: AzureMLtest
    - name: check-out-azureml-examples-repo-step
      uses: actions/checkout@v3
      with:
        repository: Azure/azureml-examples
        path: azureml-examples
    - name: azure-login-step
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - name: set-azureml-ws-context-step
      run: bash setup.sh 
      working-directory: AzureMLtest/cli
    - name: register-components-and-run-job-registry-step
      run: bash test-component.sh ${{ matrix.component_sample }} registry
      continue-on-error: true
      working-directory: AzureMLtest/cli
  
  test-environment-registry:
    #if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        env_sample: ['docker-context.yml', 'docker-image-plus-conda.yml', 'docker-image.yml' ]
    steps:
    - name: check-out-this-repo-step
      uses: actions/checkout@v2
      with:
        path: AzureMLtest
    - name: check-out-azureml-examples-repo-step
      uses: actions/checkout@v3
      with:
        repository: Azure/azureml-examples
        path: azureml-examples
    - name: azure-login-step
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - name: set-azureml-ws-context-step
      run: bash setup.sh 
      working-directory: AzureMLtest/cli
    - name: create-environment-step
      run: bash test-environment.sh ${{ matrix.env_sample }} registry
      continue-on-error: true
      working-directory: AzureMLtest/cli
